### PR TITLE
chore!: fix cancel_deferred_save event typo

### PR DESCRIPTION
**Pull request by skoch13**

### CODE REVIEW

**Review by primeapple — APPROVED** [review]
Thanks for your contribution. Looks good to me!

Fine for you @okuuva if we merge this?

**Comment by primeapple** [comment]
Ahh, just to keep in mind. This is a breaking change, as it changes the current config, so we need to communicate that.

**Comment by okuuva** [comment]
I'd love to get this fixed because now that I see the typo I can't unsee it but not sure how to deal with this. It's a breaking change and in theory we should have some grace period where both options work but old option would show a warning during plugin init. But that sounds like quite a hassle just to fix a typo...

Then again, we should have a mechanism for deprecating options, so that we could at some point get rid of execution message dimming and cleaning interval. So I think we should implement that deprecation mechanism first and apply it here before merging.

**Comment by skoch13** [comment]
You guys are the bosses here 😄 , still we can show notification when the plugin is loaded about the change, so it should not be that hard to update for those who overridden the defaults.

**Comment by primeapple** [comment]
Hi @skoch13 , to bring this forward, you would have to do the following:

1. Change the target of this PR to https://github.com/okuuva/auto-save.nvim/tree/first-breaking-changes
2. Add logic to the [handle_deprecations](https://github.com/okuuva/auto-save.nvim/blob/1747cf21c6df4806cceaa1f5f6c0ae837162f284/lua/auto-save/config.lua#L28) method, so that a warning is given to the user if they use they old `cancel_defered_save` option. Then, set the value of the new `cancel_deferred_save` option to the one of the old one and remove the old one.

If you have any questions, I can take this over as well.

**Comment by skoch13** [comment]
@primeapple thank you for your efforts and my apologies for the delay. I'm not using this plugin at the moment 😬

**Comment by primeapple** [comment]
@skoch13 It's fine, I'll merge your commit in https://github.com/okuuva/auto-save.nvim/pull/58

**Pull request closed without merging**
